# Generated by Django 4.1.1 on 2022-09-25 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.CharField(max_length=400, unique=True)),
                ('status', models.CharField(default='Subscribed', max_length=50)),
                ('cre_dt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('upd_dt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'user_emails',
                'managed': True,
            },
        ),
    ]
